from io import BytesIO
import aiohttp  
from ubot import *
from config import api_key

# Create a session if not globally defined
aiosession = aiohttp.ClientSession()

async def fetch_flux_image(question):
    url = "https://randydev-ryu-js.hf.space/api/v1/flux/black-forest-labs/flux-1-schnell"
    headers = {"x-api-key": api_key}
    params = {"query": question}
    
    async with aiosession.get(url, headers=headers, params=params) as resp:
        if resp.status == 200:
            image = BytesIO(await resp.read())
            image.name = "flux_result.jpg"
            return image
    return None

async def flux_func(client, message):
    text = (
        message.text.split(None, 1)[1]
        if len(message.command) != 1
        else None
    )
    if message.reply_to_message:
        text = message.reply_to_message.text or message.reply_to_message.caption
    if not text:
        return await message.delete()
    
    ex = await message.reply("Processing...")
    image = await fetch_flux_image(text)
    if not image:
        return await ex.edit("❌ Failed to fetch image from FLUX API.")
    
    await ex.edit("Uploading...")
    await asyncio.gather(
        ex.delete(),
        client.send_photo(
            message.chat.id,
            image,
            caption=f"<b>Generated By : </b>{client.me.mention}",
        ),
    )
    image.close()

@PY.UBOT("flux", sudo=True)
async def _(client, message):
    await flux_func(client, message)
